// <auto-generated />
using System;
using CareerSEA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareerSEA.Data.Migrations
{
    [DbContext(typeof(CareerSEADbContext))]
    [Migration("20251123034351_AddPgVector")]
    partial class AddPgVector
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareerSEA.Data.Entities.ESCO_Occupation", b =>
                {
                    b.Property<int>("ESCOId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ESCOId");

                    b.ToTable("ESCO_Occupations");
                });

            modelBuilder.Entity("CareerSEA.Data.Entities.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ESCOId")
                        .HasColumnType("integer");

                    b.Property<int?>("ESCO_OccupationESCOId")
                        .HasColumnType("integer");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ESCOId");

                    b.HasIndex("ESCO_OccupationESCOId");

                    b.HasIndex("UserId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("CareerSEA.Data.Entities.Prediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Guess")
                        .HasColumnType("double precision");

                    b.Property<string>("InputVector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("CareerSEA.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CareerSEA.Data.Entities.Experience", b =>
                {
                    b.HasOne("CareerSEA.Data.Entities.ESCO_Occupation", "ESCO_Occupation")
                        .WithMany()
                        .HasForeignKey("ESCOId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareerSEA.Data.Entities.ESCO_Occupation", null)
                        .WithMany("Experiences")
                        .HasForeignKey("ESCO_OccupationESCOId");

                    b.HasOne("CareerSEA.Data.Entities.User", "User")
                        .WithMany("Experiences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ESCO_Occupation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareerSEA.Data.Entities.Prediction", b =>
                {
                    b.HasOne("CareerSEA.Data.Entities.User", "User")
                        .WithMany("Predictions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareerSEA.Data.Entities.ESCO_Occupation", b =>
                {
                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("CareerSEA.Data.Entities.User", b =>
                {
                    b.Navigation("Experiences");

                    b.Navigation("Predictions");
                });
#pragma warning restore 612, 618
        }
    }
}
