// <auto-generated />
using System;
using CareerSEA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareerSEA.Data.Migrations
{
    [DbContext(typeof(CareerSEADbContext))]
    [Migration("20260510001041_AddSavedJobsAndResources")]
    partial class AddSavedJobsAndResources
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareerSEA.Data.Entities.ESCO_Occupation", b =>
                {
                    b.Property<int>("ESCOId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ESCOId");

                    b.ToTable("ESCO_Occupations");
                });

            modelBuilder.Entity("CareerSEA.Data.Entities.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ESCOId")
                        .HasColumnType("integer");

                    b.Property<int?>("ESCO_OccupationESCOId")
                        .HasColumnType("integer");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ESCOId");

                    b.HasIndex("ESCO_OccupationESCOId");

                    b.HasIndex("UserId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("CareerSEA.Data.Entities.Prediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("CareerSEA.Data.Entities.SavedJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Link")
                        .IsUnique();

                    b.ToTable("SavedJobs");
                });

            modelBuilder.Entity("CareerSEA.Data.Entities.SavedResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Snippet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Url")
                        .IsUnique();

                    b.ToTable("SavedResources");
                });

            modelBuilder.Entity("CareerSEA.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CareerSEA.Data.Entities.Experience", b =>
                {
                    b.HasOne("CareerSEA.Data.Entities.ESCO_Occupation", "ESCO_Occupation")
                        .WithMany()
                        .HasForeignKey("ESCOId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CareerSEA.Data.Entities.ESCO_Occupation", null)
                        .WithMany("Experiences")
                        .HasForeignKey("ESCO_OccupationESCOId");

                    b.HasOne("CareerSEA.Data.Entities.User", "User")
                        .WithMany("Experiences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ESCO_Occupation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareerSEA.Data.Entities.Prediction", b =>
                {
                    b.HasOne("CareerSEA.Data.Entities.User", "User")
                        .WithMany("Predictions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CareerSEA.Data.Entities.PredictionResult", "Result", b1 =>
                        {
                            b1.Property<Guid>("PredictionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BestJob")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "best_job");

                            b1.Property<double>("MatchScore")
                                .HasColumnType("double precision")
                                .HasAnnotation("Relational:JsonPropertyName", "match_score");

                            b1.HasKey("PredictionId");

                            b1.ToTable("Predictions");

                            b1.ToJson("Result");

                            b1.WithOwner()
                                .HasForeignKey("PredictionId");

                            b1.OwnsMany("CareerSEA.Data.Entities.JobRecommendation", "Recommendations", b2 =>
                                {
                                    b2.Property<Guid>("PredictionResultPredictionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Label")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "label");

                                    b2.Property<double>("Score")
                                        .HasColumnType("double precision")
                                        .HasAnnotation("Relational:JsonPropertyName", "score");

                                    b2.HasKey("PredictionResultPredictionId", "__synthesizedOrdinal");

                                    b2.ToTable("Predictions");

                                    b2.HasAnnotation("Relational:JsonPropertyName", "recommendations");

                                    b2.WithOwner()
                                        .HasForeignKey("PredictionResultPredictionId");
                                });

                            b1.Navigation("Recommendations");
                        });

                    b.Navigation("Result")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareerSEA.Data.Entities.SavedJob", b =>
                {
                    b.HasOne("CareerSEA.Data.Entities.User", "User")
                        .WithMany("SavedJobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareerSEA.Data.Entities.SavedResource", b =>
                {
                    b.HasOne("CareerSEA.Data.Entities.User", "User")
                        .WithMany("SavedResources")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareerSEA.Data.Entities.ESCO_Occupation", b =>
                {
                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("CareerSEA.Data.Entities.User", b =>
                {
                    b.Navigation("Experiences");

                    b.Navigation("Predictions");

                    b.Navigation("SavedJobs");

                    b.Navigation("SavedResources");
                });
#pragma warning restore 612, 618
        }
    }
}
