namespace CareerSEA.Web
{
    public static class JobTitles
    {
        public static readonly string[] Jobs = new[]
        {
            "3D modeller",
            "ATM repair technician",
            "Accommodation manager",
            "Accountant",
            "Accounting assistant",
            "Accounting manager",
            "Acoustical engineer",
            "Activism officer",
            "Activity leader",
            "Actor/actress",
            "Actuarial assistant",
            "Administrative assistant",
            "Advanced nurse practitioner",
            "Advertising assistant",
            "Advertising copywriter",
            "Advertising installer",
            "Advertising manager",
            "Advertising media planner",
            "Advertising sales agent",
            "Advertising specialist",
            "Aerospace engineer",
            "Aerospace engineering technician",
            "Aesthetician",
            "Aftersales service manager",
            "Agricultural equipment design engineer",
            "Agricultural machinery technician",
            "Agricultural scientist",
            "Agricultural technician",
            "Agriculture, forestry and fishery vocational teacher",
            "Agronomic crop production team leader",
            "Agronomist",
            "Air traffic controller",
            "Air traffic manager",
            "Aircraft assembler",
            "Aircraft cargo operations coordinator",
            "Aircraft dispatcher",
            "Aircraft engine assembler",
            "Aircraft engine tester",
            "Aircraft groomer",
            "Aircraft maintenance technician",
            "Aircraft marshaller",
            "Aircraft pilot",
            "Airport baggage handler",
            "Airport director",
            "Amusement and recreation attendant",
            "Anaesthetic technician",
            "Animal assisted therapist",
            "Animal facility manager",
            "Animal groomer",
            "Animal shelter worker",
            "Animal trainer",
            "Animal welfare inspector",
            "Animator",
            "Anthropologist",
            "Application engineer",
            "Aquaculture harvesting worker",
            "Archaeologist",
            "Architect",
            "Architectural drafter",
            "Archivist",
            "Armed forces officer",
            "Art director",
            "Art restorer",
            "Art therapist",
            "Artificial intelligence engineer",
            "Artistic painter",
            "Arts education officer",
            "Assayer",
            "Assistant clinical psychologist",
            "Assistant lecturer",
            "Assistant stage director",
            "Assistant video and motion picture director",
            "Astronomer",
            "Audio and video equipment specialised seller",
            "Audio production technician",
            "Audio-visual technician",
            "Audiology equipment specialised seller",
            "Audit supervisor",
            "Auditing clerk",
            "Automated cable vehicle controller",
            "Automation engineer",
            "Automation engineering technician",
            "Automotive brake technician",
            "Automotive electrician",
            "Automotive engineer",
            "Automotive engineering technician",
            "Automotive test driver",
            "Auxiliary nursing and midwifery vocational teacher",
            "Avionics technician",
            "Baggage flow supervisor",
            "Baker",
            "Bakery specialised seller",
            "Bank account manager",
            "Bank manager",
            "Bank teller",
            "Bartender",
            "Bicycle assembler",
            "Bicycle courier",
            "Bicycle mechanic",
            "Bindery operator",
            "Biochemist",
            "Bioinformatics scientist",
            "Biologist",
            "Biophysicist",
            "Biotechnical technician",
            "Blacksmith",
            "Block machine operator",
            "Body artist",
            "Boiler operator",
            "Boilermaker",
            "Book publisher",
            "Bookkeeper",
            "Bookshop specialised seller",
            "Boxing instructor",
            "Branch manager",
            "Brand manager",
            "Brew house operator",
            "Brewmaster",
            "Bricklayer",
            "Broadcast technician",
            "Building caretaker",
            "Building cleaner",
            "Building construction worker",
            "Building information modelling consultant",
            "Building inspector",
            "Building materials specialised seller",
            "Bulldozer operator",
            "Bus driver",
            "Bus route supervisor",
            "Business analyst",
            "Business coach",
            "Business consultant",
            "Business developer",
            "Business economics researcher",
            "Business intelligence manager",
            "Business manager",
            "Butcher",
            "Cabin crew manager",
            "Cabinet maker",
            "Cable jointer",
            "Calculation engineer",
            "Call centre agent",
            "Call centre manager",
            "Call centre supervisor",
            "Camping ground manager",
            "Canvas goods assembler",
            "Car leasing agent",
            "Care home worker",
            "Career guidance advisor",
            "Cargo vehicle driver",
            "Carpenter",
            "Carpenter supervisor",
            "Carriage driver",
            "Case administrator",
            "Cashier",
            "Casino cashier",
            "Casting mould maker",
            "Cattle breeder",
            "Ceiling installer",
            "Cemetery attendant",
            "Ceramicist",
            "Checkout supervisor",
            "Chef",
            "Chemical engineer",
            "Chemical engineering technician",
            "Chemical manufacturing quality technician",
            "Chemical metallurgist",
            "Chemical mixer",
            "Chemical processing supervisor",
            "Chemist",
            "Chemistry technician",
            "Chief ICT security officer",
            "Chief executive officer",
            "Chief information officer",
            "Chief technology officer",
            "Child care coordinator",
            "Child care social worker",
            "Child care worker",
            "Chimney sweep",
            "Chimney sweep supervisor",
            "Choreographer",
            "Circus artist",
            "City councillor",
            "Civil drafter",
            "Civil enforcement officer",
            "Civil engineer",
            "Civil engineering technician",
            "Civil engineering worker",
            "Civil service administrative officer",
            "Client relations manager",
            "Clinical coder",
            "Clinical informatics manager",
            "Clinical perfusion scientist",
            "Clinical psychologist",
            "Clinical trial assistant",
            "Clock and watchmaker",
            "Clothing alteration machinist",
            "Clothing cutter",
            "Clothing fashion designer",
            "Clothing technologist",
            "Cloud DevOps engineer",
            "Cloud architect",
            "Club host/club hostess",
            "Coachbuilder",
            "Coating machine operator",
            "Collection manager",
            "Colour sampling technician",
            "Commercial director",
            "Commercial pilot",
            "Commercial sales representative",
            "Commissioning engineer",
            "Commissioning technician",
            "Commodity broker",
            "Communication infrastructure maintainer",
            "Communication manager",
            "Communication scientist",
            "Community development officer",
            "Community health worker",
            "Community social worker",
            "Complementary therapist",
            "Compliance engineer",
            "Composer",
            "Compression moulding machine operator",
            "Computer games, multimedia and software specialised seller",
            "Computer hardware engineer",
            "Computer hardware test technician",
            "Computer numerical control machine operator",
            "Computer scientist",
            "Computer-aided design operator",
            "Concrete finisher",
            "Concrete finisher supervisor",
            "Concrete products machine operator",
            "Construction commercial diver",
            "Construction engineer",
            "Construction equipment technician",
            "Construction general contractor",
            "Construction general supervisor",
            "Construction manager",
            "Construction painter",
            "Construction painting supervisor",
            "Construction quality manager",
            "Construction safety inspector",
            "Construction scaffolder",
            "Construction scaffolding supervisor",
            "Consumer electronics repair technician",
            "Consumer goods inspector",
            "Consumer rights advisor",
            "Contact centre supervisor",
            "Conveyance clerk",
            "Cook",
            "Copy editor",
            "Corporate banking adviser",
            "Corporate social responsibility manager",
            "Corporate trainer",
            "Corrosion technician",
            "Cosmetics and perfume specialised seller",
            "Cost analyst",
            "Costume attendant",
            "Costume buyer",
            "Costume designer",
            "Court administrative officer",
            "Court administrator",
            "Court bailiff",
            "Court enforcement officer",
            "Crane technician",
            "Credit adviser",
            "Credit manager",
            "Criminal investigator",
            "Criminologist",
            "Critic",
            "Crop production worker",
            "Cultural centre director",
            "Cultural facilities manager",
            "Cultural policy officer",
            "Customer contact centre information clerk",
            "Customer experience manager",
            "Customs officer",
            "Cybersecurity risk manager",
            "Cylinder filler",
            "Cytotechnologist",
            "Dairy processing operator",
            "Dairy processing technician",
            "Dairy products maker",
            "Dance teacher",
            "Dance therapist",
            "Dancer",
            "Dangerous goods safety adviser",
            "Data analyst",
            "Data centre operator",
            "Data engineer",
            "Data entry clerk",
            "Data protection officer",
            "Data scientist",
            "Data warehouse designer",
            "Database integrator",
            "Debt collector",
            "Deck officer",
            "Decorative painter",
            "Delicatessen specialised seller",
            "Demographer",
            "Demolition worker",
            "Dental chairside assistant",
            "Dental hygienist",
            "Dental practitioner",
            "Dental technician",
            "Department manager",
            "Design engineer",
            "Destination manager",
            "Diesel engine mechanic",
            "Diet cook",
            "Dietetic technician",
            "Dietitian",
            "Digital forensics expert",
            "Digital games designer",
            "Digital literacy teacher",
            "Digital marketing manager",
            "Digital media designer",
            "Digital printer",
            "Digital transformation manager",
            "Director of photography",
            "Disability support worker",
            "Disc jockey",
            "Dismantling engineer",
            "Dismantling worker",
            "Distillery miller",
            "Distillery supervisor",
            "Doctors' surgery assistant",
            "Dog trainer",
            "Domestic cleaner",
            "Domestic electrician",
            "Domestic energy assessor",
            "Domestic housekeeper",
            "Door to door seller",
            "Doorman/doorwoman",
            "Drafter",
            "Drain technician",
            "Drama teacher",
            "Dramaturge",
            "Drawing artist",
            "Drill operator",
            "Driving instructor",
            "Drug and alcohol addiction counsellor",
            "Dry press operator",
            "e-learning developer",
            "eBusiness manager",
            "Early years teacher",
            "Early years teaching assistant",
            "Ecologist",
            "Economist",
            "Editor-in-chief",
            "Editorial assistant",
            "Education inspector",
            "Education policy officer",
            "Education programme coordinator",
            "Educational counsellor",
            "Educational psychologist",
            "Educational researcher",
            "Elderly home manager",
            "Electric power generation engineer",
            "Electrical engineer",
            "Electrical engineering technician",
            "Electrical equipment production supervisor",
            "Electrician",
            "Electromechanical engineering technician",
            "Electron beam welder",
            "Electronic equipment inspector",
            "Electronics drafter",
            "Electronics engineer",
            "Electronics engineering technician",
            "Electronics production supervisor",
            "Embedded systems software developer",
            "Embroiderer",
            "Emergency ambulance driver",
            "Employment agent",
            "Employment support worker",
            "Energy consultant",
            "Energy manager",
            "Engine designer",
            "Engineering assistant",
            "Enterprise architect",
            "Environmental engineer",
            "Environmental health inspector",
            "Environmental programme coordinator",
            "Environmental scientist",
            "Environmental technician",
            "Equality and inclusion manager",
            "Equine yard manager",
            "Event manager",
            "Exhibition curator",
            "Extra",
            "Factory hand",
            "Family planning counsellor",
            "Farm manager",
            "Farrier",
            "Fashion designer",
            "Fashion model",
            "Fermenter operator",
            "File clerk",
            "Financial auditor",
            "Financial broker",
            "Financial controller",
            "Financial fraud examiner",
            "Financial manager",
            "Financial planner",
            "Fire protection technician",
            "Firefighter",
            "Fireplace installer",
            "First aid instructor",
            "Fisheries boatman",
            "Fitness instructor",
            "Fitter and turner",
            "Flight attendant",
            "Flight instructor",
            "Flower and garden specialised seller",
            "Fluid power technician",
            "Food analyst",
            "Food production operator",
            "Food safety inspector",
            "Food service worker",
            "Food technologist",
            "Football coach",
            "Footwear assembly supervisor",
            "Footwear production supervisor",
            "Footwear stitching machine operator",
            "Foreclosure specialist",
            "Foreign language correspondence clerk",
            "Forest ranger",
            "Forest worker",
            "Forester",
            "Forestry equipment operator",
            "Forestry technician",
            "Forklift operator",
            "Forwarding manager",
            "Foster care support worker",
            "Foundry operative",
            "Frame maker",
            "Freight transport dispatcher",
            "Fruit and vegetable canner",
            "Fruit production team leader",
            "Fuel station specialised seller",
            "Fundraising manager",
            "Funeral services director",
            "Furniture assembler",
            "Furniture finisher",
            "Furniture restorer",
            "Furniture specialised seller",
            "Further education principal",
            "Further education teacher",
            "Gaming dealer",
            "Gaming inspector",
            "Garage manager",
            "Garden labourer",
            "Gate guard",
            "General practitioner",
            "General veterinarian",
            "Geographer",
            "Geographic information systems specialist",
            "Geologist",
            "Geology technician",
            "Geophysicist",
            "Geotechnician",
            "Glass beveller",
            "Glass forming machine operator",
            "Glass installation supervisor",
            "Glass painter",
            "Glass-blower",
            "Goldsmith",
            "Golf instructor",
            "Graphic designer",
            "Green ICT consultant",
            "Groom",
            "Ground steward/ground stewardess",
            "Gunsmith",
            "Hairdresser",
            "Hand packer",
            "Hardwood floor layer",
            "Head chef",
            "Head waiter/head waitress",
            "Headteacher",
            "Health and safety engineer",
            "Health and safety inspector",
            "Health and safety officer",
            "Health psychologist",
            "Health safety and environmental manager",
            "Healthcare assistant",
            "Healthcare inspector",
            "Healthcare institution manager",
            "Heating and ventilation service installer",
            "Heating technician",
            "Heating, ventilation, air conditioning engineer",
            "Helicopter pilot",
            "Helmsman",
            "Higher education lecturer",
            "Historian",
            "Home care aide",
            "Horse breeder",
            "Horse riding instructor",
            "Horse trainer",
            "Horticulture production manager",
            "Horticulture production team leader",
            "Horticulture worker",
            "Hospital porter",
            "Hospitality establishment receptionist",
            "Hospitality revenue manager",
            "Hotel butler",
            "Hotel porter",
            "House builder",
            "House sitter",
            "Household appliances repair technician",
            "Housekeeping supervisor",
            "Housing manager",
            "Human resources assistant",
            "Human resources manager",
            "Human resources officer",
            "Hydrologist",
            "ICT account manager",
            "ICT application configurator",
            "ICT application developer",
            "ICT auditor manager",
            "ICT business analysis manager",
            "ICT business development manager",
            "ICT buyer",
            "ICT capacity planner",
            "ICT change and configuration manager",
            "ICT documentation manager",
            "ICT help desk agent",
            "ICT help desk manager",
            "ICT network administrator",
            "ICT network technician",
            "ICT operations manager",
            "ICT project manager",
            "ICT quality assurance manager",
            "ICT research manager",
            "ICT system administrator",
            "ICT system analyst",
            "ICT system developer",
            "ICT system tester",
            "ICT test analyst",
            "ICT trainer",
            "ICT vendor relationship manager",
            "Imagesetter",
            "Import export manager",
            "Import export specialist",
            "Industrial cook",
            "Industrial designer",
            "Industrial electrician",
            "Industrial engineer",
            "Industrial engineering technician",
            "Industrial firefighter",
            "Industrial machinery mechanic",
            "Industrial maintenance supervisor",
            "Industrial pharmacist",
            "Industrial production manager",
            "Industrial quality manager",
            "Information manager",
            "Injection moulding operator",
            "Instrumentation engineer",
            "Instrumentation engineering technician",
            "Insulation worker",
            "Insurance agency manager",
            "Insurance broker",
            "Insurance claims manager",
            "Insurance clerk",
            "Insurance fraud investigator",
            "Insurance rating analyst",
            "Insurance underwriter",
            "Integration engineer",
            "Intellectual property consultant",
            "Intercultural communication consultant",
            "Interior architect",
            "Interior designer",
            "Interior planner",
            "Interpreter",
            "Inventory coordinator",
            "Investment adviser",
            "Investment fund manager",
            "Investor relations manager",
            "Jeweller",
            "Jewellery and watches specialised seller",
            "Jewellery designer",
            "Jewellery polisher",
            "Journalist",
            "Judge",
            "Kennel worker",
            "Kiln firer",
            "Kitchen assistant",
            "Kitchen porter",
            "Labour market policy officer",
            "Lacquer maker",
            "Land surveyor",
            "Land-based machinery operator",
            "Land-based machinery technician",
            "Landscape architect",
            "Landscape gardener",
            "Language school teacher",
            "Laser marking machine operator",
            "Laundromat attendant",
            "Laundry and dry cleaning manager",
            "Laundry worker",
            "Lawyer",
            "Lawyer linguist",
            "Lean manager",
            "Learning support teacher",
            "Leather goods finishing operator",
            "Leather laboratory technician",
            "Legal administrative assistant",
            "Legal assistant",
            "Legal consultant",
            "Legal guardian",
            "Leisure attendant",
            "Librarian",
            "Library assistant",
            "Lieutenant",
            "Life guard",
            "Lift technician",
            "Light board operator",
            "Linguist",
            "Literary scholar",
            "Live chat operator",
            "Livestock worker",
            "Loan officer",
            "Localiser",
            "Logistics analyst",
            "Logistics and distribution manager",
            "Lottery cashier",
            "Machine operator supervisor",
            "Machinery assembly coordinator",
            "Made-up textile articles manufacturer",
            "Mail clerk",
            "Maintenance and repair engineer",
            "Make-up and hair designer",
            "Make-up artist",
            "Malt house supervisor",
            "Management assistant",
            "Manicurist",
            "Manufactured wooden building assembler",
            "Manufacturing engineer",
            "Manufacturing manager",
            "Marine biologist",
            "Marine chief engineer",
            "Marine electrician",
            "Marine engineer",
            "Marine mechanic",
            "Marine surveyor",
            "Maritime pilot",
            "Market research analyst",
            "Market research interviewer",
            "Marketing assistant",
            "Marketing consultant",
            "Massage therapist",
            "Material testing technician",
            "Materials engineer",
            "Mathematician",
            "Meat and meat products specialised seller",
            "Mechanical engineer",
            "Mechanical engineering drafter",
            "Mechanical engineering technician",
            "Mechatronics assembler",
            "Mechatronics engineer",
            "Mechatronics engineering technician",
            "Media scientist",
            "Mediator",
            "Medical administrative assistant",
            "Medical device assembler",
            "Medical device engineer",
            "Medical device engineering technician",
            "Medical laboratory assistant",
            "Medical laboratory manager",
            "Medical laboratory technology vocational teacher",
            "Medical practice manager",
            "Medical records clerk",
            "Medical records manager",
            "Medical sales representative",
            "Medical transcriptionist",
            "Membership manager",
            "Mental health social worker",
            "Mergers and acquisitions analyst",
            "Metal additive manufacturing operator",
            "Metal drawing machine operator",
            "Metal engraver",
            "Metal nibbling operator",
            "Metal production supervisor",
            "Metal products assembler",
            "Metal sawing machine operator",
            "Metallurgical manager",
            "Metallurgical technician",
            "Meteorologist",
            "Meter reader",
            "Microbiologist",
            "Microelectronics engineer",
            "Microelectronics engineering technician",
            "Microsystem engineering technician",
            "Midwife",
            "Milliner",
            "Mine development engineer",
            "Mineral crushing operator",
            "Mineral processing engineer",
            "Mineral processing operator",
            "Mineralogist",
            "Mining assistant",
            "Mining geotechnical engineer",
            "Minister of religion",
            "Missionary",
            "Mixed farmer",
            "Mobility services manager",
            "Motor vehicle assembly supervisor",
            "Motor vehicle parts assembler",
            "Motor vehicle upholsterer",
            "Motor vehicles parts advisor",
            "Motor vehicles specialised seller",
            "Motorcycle assembler",
            "Mountain guide",
            "Move coordinator",
            "Mover",
            "Museum director",
            "Museum scientist",
            "Music and video shop specialised seller",
            "Music director",
            "Music teacher",
            "Music therapist",
            "Musical conductor",
            "Musician",
            "Mutual fund broker",
            "Nanny",
            "Nanoengineer",
            "Nature conservation officer",
            "News anchor",
            "Night auditor",
            "Numerical tool and process control programmer",
            "Nurse assistant",
            "Nursery school head teacher",
            "Occupational health and safety inspector",
            "Occupational therapist",
            "Office clerk",
            "Office manager",
            "Offshore renewable energy technician",
            "Online community manager",
            "Online marketer",
            "Onshore wind energy engineer",
            "Operations manager",
            "Optical instrument assembler",
            "Optical instrument repairer",
            "Optical technician",
            "Optician",
            "Optomechanical engineering technician",
            "Optometrist",
            "Ornamental metal worker",
            "Orthopaedic footwear technician",
            "Orthopaedic supplies specialised seller",
            "Orthoptist",
            "Osteopath",
            "Oxy fuel burning machine operator",
            "Packaging production manager",
            "Packing machinery engineer",
            "Paper machine operator",
            "Paper stationery machine operator",
            "Paramedic in emergency responses",
            "Pastoral worker",
            "Pastry chef",
            "Pastry maker",
            "Patent engineer",
            "Payroll clerk",
            "Pensions administrator",
            "Performance lighting technician",
            "Personal property appraiser",
            "Personal stylist",
            "Personal trainer",
            "Pest management worker",
            "Pet and pet food specialised seller",
            "Pharmaceutical engineer",
            "Pharmacist",
            "Pharmacologist",
            "Pharmacy assistant",
            "Philosopher",
            "Photographer",
            "Photographic developer",
            "Photonics engineering technician",
            "Physicist",
            "Physics technician",
            "Physiotherapist",
            "Picture editor",
            "Pig breeder",
            "Pipe welder",
            "Pipeline compliance coordinator",
            "Pipeline maintenance worker",
            "Plasterer",
            "Plastic and rubber products manufacturing supervisor",
            "Plastic rolling machine operator",
            "Plate glass installer",
            "Plumber",
            "Podiatrist",
            "Police detective",
            "Police inspector",
            "Police officer",
            "Political party agent",
            "Political scientist",
            "Port coordinator",
            "Postman/postwoman",
            "Pottery and porcelain caster",
            "Poultry breeder",
            "Power plant control room operator",
            "Power production plant operator",
            "Power tool repair technician",
            "Precious stone cutter",
            "Precision engineer",
            "Precision mechanics supervisor",
            "Prepress technician",
            "Presenter",
            "Pricing specialist",
            "Primary school teacher",
            "Printed circuit board assembler",
            "Prison officer",
            "Private chauffeur",
            "Private detective",
            "Process engineer",
            "Process engineering technician",
            "Process officer",
            "Producer",
            "Product and services manager",
            "Product assembly inspector",
            "Product development engineering drafter",
            "Product development engineering technician",
            "Product manager",
            "Product quality controller",
            "Production engineer",
            "Production plant crane operator",
            "Production supervisor",
            "Professional athlete",
            "Project manager",
            "Project support officer",
            "Promotion manager",
            "Promotions demonstrator",
            "Prompter",
            "Proofreader",
            "Prop master/prop mistress",
            "Property acquisitions manager",
            "Property assistant",
            "Prosecutor",
            "Prosthetic-orthotics technician",
            "Psychologist",
            "Psychotherapist",
            "Public affairs consultant",
            "Public relations manager",
            "Public relations officer",
            "Public speaking coach",
            "Punch press operator",
            "Puppeteer",
            "Purchaser",
            "Purchasing manager",
            "Quality engineer",
            "Quality engineering technician",
            "Quality services manager",
            "Quantity surveyor",
            "Radiation protection officer",
            "Radiation therapist",
            "Radio technician",
            "Rail layer",
            "Rail logistics coordinator",
            "Rail operations manager",
            "Rail project engineer",
            "Rail traffic controller",
            "Raw materials warehouse specialist",
            "Real estate agent",
            "Real estate manager",
            "Real estate surveyor",
            "Receptionist",
            "Recreation policy officer",
            "Recycling worker",
            "Refrigeration air condition and heat pump technician",
            "Refurbishing technician",
            "Regulatory affairs manager",
            "Religion scientific researcher",
            "Relocation officer",
            "Renewable energy consultant",
            "Rental service representative in cars and light motor vehicles",
            "Rescue centre manager",
            "Research and development manager",
            "Research engineer",
            "Residential home adult care worker",
            "Resilient floor layer",
            "Restaurant host/restaurant hostess",
            "Restaurant manager",
            "Road construction supervisor",
            "Road construction worker",
            "Road maintenance technician",
            "Road marker",
            "Road transport division manager",
            "Roadside vehicle technician",
            "Robotics engineer",
            "Robotics engineering technician",
            "Rolling stock inspector",
            "Roofer",
            "Roofing supervisor",
            "Rooms division manager",
            "Roughneck",
            "Sales account manager",
            "Sales assistant",
            "Sales engineer",
            "Sales manager",
            "Sales processor",
            "Sales support assistant",
            "Scenic painter",
            "Scientific laboratory technician",
            "Screen making technician",
            "Screen printer",
            "Script supervisor",
            "Script writer",
            "Sculptor",
            "Second-hand goods specialised seller",
            "Secondary school head teacher",
            "Secondary school teacher",
            "Secretary",
            "Securities analyst",
            "Securities broker",
            "Securities underwriter",
            "Security alarm technician",
            "Security guard",
            "Sensor engineer",
            "Sergeant",
            "Set builder",
            "Set designer",
            "Sewer construction supervisor",
            "Sewer construction worker",
            "Sewerage network operative",
            "Sewing machinist",
            "Shelf filler",
            "Shepherd",
            "Ship captain",
            "Ship duty engineer",
            "Ship pilot dispatcher",
            "Shipwright",
            "Shoe and leather accessories specialised seller",
            "Shoemaker",
            "Shop supervisor",
            "Shotfirer",
            "Shunter",
            "Sign maker",
            "Singer",
            "Ski instructor",
            "Smart home installer",
            "Social counsellor",
            "Social pedagogue",
            "Social security officer",
            "Social work assistant",
            "Social work researcher",
            "Social worker",
            "Sociologist",
            "Software architect",
            "Software developer",
            "Solar energy technician",
            "Solderer",
            "Sommelier",
            "Sound operator",
            "Spa attendant",
            "Special educational needs coordinator",
            "Special educational needs teacher",
            "Special educational needs teacher secondary school",
            "Special-interest groups' official",
            "Specialised antique dealer",
            "Specialised doctor",
            "Specialised seller",
            "Specialist biomedical scientist",
            "Specialist chiropractor",
            "Specialist dentist",
            "Specialist nurse",
            "Specialist pharmacist",
            "Speech and language therapist",
            "Spokesperson",
            "Sport facility manager",
            "Sport therapist",
            "Sporting accessories specialised seller",
            "Sports coach",
            "Sports instructor",
            "Stage director",
            "Stage manager",
            "Stage technician",
            "Stamping press operator",
            "Stand-up comedian",
            "Statistician",
            "Steeplejack",
            "Steiner school teacher",
            "Steward/stewardess",
            "Stock trader",
            "Stone planer",
            "Stonemason",
            "Strategic planning manager",
            "Street food vendor",
            "Structural ironworker",
            "Supply chain manager",
            "Surface miner",
            "Surgical instrument maker",
            "Surveying technician",
            "Swimming facility attendant",
            "Swimming teacher",
            "Synthetic materials engineer",
            "Talent agent",
            "Tanning consultant",
            "Tanning technician",
            "Tax advisor",
            "Tax clerk",
            "Tax compliance officer",
            "Taxi controller",
            "Taxi driver",
            "Taxidermist",
            "Technical communicator",
            "Technical director",
            "Technical sales representative",
            "Technical sales representative in electronic and telecommunications equipment",
            "Telecommunications engineer",
            "Telecommunications engineering technician",
            "Telecommunications equipment maintainer",
            "Telecommunications technician",
            "Telephone switchboard operator",
            "Tennis coach",
            "Textile designer",
            "Textile finishing machine operator",
            "Textile machine operator",
            "Textile machinery technician",
            "Textile operations manager",
            "Textile quality inspector",
            "Textile quality technician",
            "Textile sourcing merchandiser",
            "Textile specialised seller",
            "Textile, leather and footwear researcher",
            "Ticket issuing clerk",
            "Tile fitter",
            "Tiling supervisor",
            "Tool and die maker",
            "Tour operator representative",
            "Tourism policy director",
            "Tourism product manager",
            "Tourist animator",
            "Tourist guide",
            "Tourist information officer",
            "Toymaker",
            "Toys and games specialised seller",
            "Train cleaner",
            "Train conductor",
            "Train driver",
            "Translator",
            "Transport engineer",
            "Transport equipment painter",
            "Transport planner",
            "Travel consultant",
            "Tree surgeon",
            "Tunnel boring machine operator",
            "Tutor",
            "Twisting machine operator",
            "Typist",
            "Tyre fitter",
            "Underground heavy equipment operator",
            "University research assistant",
            "Upholsterer",
            "Urban planner",
            "User interface designer",
            "Usher",
            "Vehicle cleaner",
            "Vehicle maintenance attendant",
            "Vehicle restoration technician",
            "Vehicle technician",
            "Venture capitalist",
            "Venue programmer",
            "Verger",
            "Vessel steering instructor",
            "Veterinary technician",
            "Video and motion picture producer",
            "Video artist",
            "Vineyard cellar master",
            "Vineyard manager",
            "Visual merchandiser",
            "Viticulture adviser",
            "Vocational teacher",
            "Voice-over artist",
            "Volunteer mentor",
            "Waiter/waitress",
            "Waste management officer",
            "Waste treatment engineer",
            "Wastewater treatment technician",
            "Water engineer",
            "Water network operative",
            "Water systems engineering technician",
            "Water traffic coordinator",
            "Wearing apparel patternmaker",
            "Wearing apparel presser",
            "Weaving machine operator",
            "Web content manager",
            "Web designer",
            "Web developer",
            "Weight loss consultant",
            "Welder",
            "Welding coordinator",
            "Welding engineer",
            "Welding inspector",
            "Well-digger",
            "Wind musical instrument maker",
            "Wine fermenter",
            "Wood assembly supervisor",
            "Wood caulker",
            "Wood production supervisor",
            "Wood technology engineer",
            "Woodcarver",
            "Wooden furniture machine operator",
            "Woodturner",
            "Yeast distiller",
            "Youth worker",
            "Zookeeper"
        };
    }
}